spring.application.name=duriu-open

## R2DBC Postgres connection (matches compose.yaml service)
#spring.r2dbc.url=r2dbc:postgresql://postgres:5432/mydatabase
#spring.r2dbc.username=myuser
#spring.r2dbc.password=secret

spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}

# Use Flyway or schema initialization via SQL scripts. Spring Boot will run schema.sql on startup for R2DBC
spring.sql.init.mode=always
spring.sql.init.platform=postgresql

# Logging
logging.level.org.springframework.r2dbc=DEBUG

# Render port binding
server.port=${PORT:8080}
server.address=0.0.0.0
